-- CREATE APP_USER TABLE (renamed from USER - reserved keyword in H2 2.x)
CREATE TABLE IF NOT EXISTS APP_USER (
    USER_ID VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255),
    PASSWORD VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID)
);

-- CREATE ROLE TABLE
CREATE TABLE IF NOT EXISTS ROLE (
    ROLE_ID VARCHAR(255) NOT NULL,
    ROLE_DESCRIPTION VARCHAR(255),
    ROLE_NAME VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_ID)
);

-- CREATE USER-ROLES MAPPING TABLE
CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID VARCHAR(255) NOT NULL,
    ROLE_ID VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- OAuth client details table (used by Spring Authorization Server client registration)
CREATE TABLE IF NOT EXISTS oauth_client_details (
    CLIENT_ID VARCHAR(255) NOT NULL,
    CLIENT_SECRET VARCHAR(255) NOT NULL,
    authorized_grant_types VARCHAR(255),
    authorities VARCHAR(255),
    scope VARCHAR(255),
    resource_ids VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CLIENT_ID)
);
