apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  STRIPE_SECRET_KEY: {{ .Values.paymentService.stripeSecretKey | quote }}
  JWT_KEYSTORE_PASSWORD: {{ .Values.accountService.jwtKeystorePassword | quote }}
  JWT_KEY_PAIR_PASSWORD: {{ .Values.accountService.jwtKeyPairPassword | quote }}
